POST http://localhost:5235/Tenant
Content-Type: application/json

{
  "id": "1",
  "identifier": "Apple",
  "name": "Apple"
 }

###
POST http://localhost:5235/todo
tenant: Apple
Content-Type: application/json

 {
  "id": 0,
  "name": "mssqp",
  "description": "testing mssql",
  "status": "working",
  "isComplete": false
}