GET http://localhost:7021/Tenant
Content-Type: application/json
###
POST http://localhost:7021/Tenant
Content-Type: application/json

{
  "id": "1",
  "identifier": "apl",
  "name": "apl"
 }

###
POST http://localhost:7021/todo
tenant: apl
Content-Type: application/json

 {
  "id": 0,
  "name": "mssqp",
  "description": "testing mssql",
  "status": "working",
  "isComplete": false
}
###
GET  http://localhost:7021/todos
tenant: apl
Content-Type: application/json
###
GET  http://localhost:7021/todo/1
tenant: apl
Content-Type: application/json
